# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 103395e8c03b9f83a25bb87d97c8ed1fa118089a147802376095dbe5a167f185b5c2f6577ac2e595dbfb6d7ed074a77c8166c614b4556e1e0a9740dca573640a

test:
  secret_key_base: 219c41db5e162de966d64150f4b66b5d6a1b452d7dad8913b05b6a62b382d0c069854fa80dc1d62ae52b4bf540880102d2ea7d2115ef7e3b5fe1935cd2c37c68

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
